baseURL = "https://example.com/"
languageCode = "en-us"
title = "Almir Hadzic"
theme = "hugo-profile"

[markup]
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    workingFolderCurrent = true
[security.exec]
allow = ["asciidoctor", "^(dart-)?sass(-embedded)?$", "^go$", "^npx$", "^postcss$"]

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 10

  
  

